#!/bin/bash

set -e
export PGUSER="$POSTGRES_USER"

"${psql[@]}"" --dbname "$POSTGRES_DB" <<- 'EOSQL'
    CREATE DATABASE ${POSTGRES_TEST_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_TEST_DB} TO ${POSTGRES_USER};
EOSQL
