version: "3.7"

services:
  mailhog:
    container_name: "stellar_mailhog"
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "10250:1025"

  postgres:
    container_name: "stellar_pgsql"
    image: mdillon/postgis
    environment:
      POSTGRES_USER: stellar
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stellar
    restart: unless-stopped
    ports:
      - "54320:5432"
    volumes:
      - ./scripts/pgsql:/scripts/
      - ./scripts/setup-pgsql.sh:/usr/local/bin/setup.sh

  mysql:
    container_name: "stellar_mysql"
    image: mysql:8
    ports:
      - "33060:3306"
    volumes:
      - ./scripts/mysql:/scripts/
      - ./docker/mysql:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: stellar
      MYSQL_USER: stellar
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: stellar
    restart: unless-stopped

  redis:
    container_name: "stellar_redis"
    image: redis:alpine
    ports:
      - "63790:6379"
    restart: unless-stopped

networks:
  default:
    name: stellar-network
