version: "3.7"

services:
  web:
    container_name: "${PREFIX}_web"
    image: nginx:alpine
    working_dir: /src
    ports:
      - "${WEB_PORT:-8000}:80"
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - "${BACKEND_PATH}:/src"
    links:
      - php

  artisan:
    container_name: "${PREFIX}_artisan"
    image: stellarcli/php-cli
    entrypoint:
      - php
      - artisan
    user: ${CURRENT_UID}
    working_dir: /src
    volumes:
      - "${BACKEND_PATH}:/src"

  phpunit:
    container_name: "${PREFIX}_phpunit"
    image: stellarcli/php-cli
    entrypoint:
      - vendor/bin/phpunit
    user: ${CURRENT_UID}
    working_dir: /src
    volumes:
      - "${BACKEND_PATH}:/src"

  php:
    container_name: "${PREFIX}_php"
    image: stellarcli/php-fpm
    working_dir: /src
    user: ${CURRENT_UID}
    volumes:
      - "${BACKEND_PATH}:/src"
      - ./docker/php/overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

networks:
  default:
    external:
      name: stellar-network
