version: "3.7"

services:
  mailhog:
    container_name: "stellar_mailhog"
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "10250:1025"

  postgres:
    container_name: "stellar_pgsql"
    image: mdillon/postgis
    environment:
      POSTGRES_USER: stellar
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stellar
      POSTGRES_TEST_DB: test
    restart: unless-stopped
    ports:
      - "54320:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  mysql:
    container_name: "stellar_mysql"
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stellar
      MYSQL_USER: stellar
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: stellar
    restart: unless-stopped

  redis:
    container_name: "stellar_redis"
    ports:
      - "63790:6379"
    image: redis:alpine

networks:
  default:
    name: stellar-network
