#!/usr/bin/env bash
export STELLAR_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
export CURRENT_UID=$(id -u):$(id -g)

find_up () {
  path=$(pwd)
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  echo "$path"
}

container_list () {
    echo "CONTAINERS:"
    echo "web           ${PREFIX}_web"
    echo "redis         ${PREFIX}_redis"
    echo "artisan       ${PREFIX}_artisan"
    echo "phpunit       ${PREFIX}_phpunit"
    echo "php           ${PREFIX}_php"
    echo "mailhog       ${PREFIX}_mailhog"
    if [[ -z ${MYSQL_PORT} ]]; then
        echo "pgsql         ${PREFIX}_pgsql"
        echo "pgadmin       ${PREFIX}_pgadmin"
    else
        echo "mysql         ${PREFIX}_mysql"
    fi
}

init() {
    if [[ -f ".stellar" ]]; then
        export BACKEND_PATH="$( pwd -P)"
    else
        export BACKEND_PATH="$( find_up  .stellar )"
    fi
    set -a
        source "${BACKEND_PATH}/.stellar"
    set +a
    if [[ $# -gt 0 ]]; then
        start_command "${@}"
    else
        echo "init                 Init Stellar."
        echo "start                Start Stellar."
        echo "refresh              Refresh Stellar."
        echo "artisan              Pass through command to php artisan."
        echo "test                 Run phpunit tests."
    fi
}

start_command() {

    if [[ -z ${MYSQL_PORT} ]]; then
        container='web'
    else
        container='web_mysql'
    fi

    if [[ ${1} == "init" ]]; then
        run_command docker-compose up -d ${container}
        container_list
    elif [[ "${1}" == "refresh" ]]; then
        run_command docker-compose down
        run_command docker-compose build --no-cache php phpunit artisan
        run_command docker-compose up -d --force-recreate ${container}
        container_list
    elif [[ "${1}" == "start" ]]; then
        run_command docker-compose up -d ${container}
        container_list
    elif [[ "${1}" == "artisan" ]]; then
        shift 1
        dcr artisan "${@}"
    elif [[ "${1}" == "test" ]]; then
        shift 1
        dcr  phpunit "${@}"
    elif [[ "${1}" == "list" ]]; then
        container_list
    elif [[  $# -gt 0 ]]; then
        run_command docker-compose "${@}"
    fi
    exit 0
}

dcr() {
    run_command docker-compose run --rm  "${@}"
}

run_command() {
  if [[ $# -gt 0 ]]; then
    (cd ${STELLAR_PATH}  && $*)
  fi
}

init "${@}"
