#!/usr/bin/env bash

set -e
export PGUSER="${POSTGRES_USER}"

psql <<EOF
    CREATE DATABASE ${DB_NAME};
    CREATE USER ${DB_USERNAME} WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USERNAME};
EOF
